//! Two independent checks on `krusty_kms_crypto::ml_dsa`, plus the shape rules the Cairo
//! account depends on.
//!
//! 1. **Known answers** from ml-dsa-cairo (`mldsa/src/vector.cairo`,
//!    `packed_key.cairo`, generated by `py/gen_vectors.py`) — the reference the
//!    Cairo verifier was written against. The fixture pins a Poseidon digest per
//!    payload section, so a mismatch says *which* section drifted rather than
//!    just that the payload is wrong.
//! 2. **`fips204`**, a second FIPS 204 implementation, signing freshly generated
//!    keys so this verifier is checked against something that is not itself.
//!    Deterministic: the keygen RNG below is seeded, never the OS.

use fips204::ml_dsa_65;
use fips204::traits::{SerDes, Signer, Verifier};
use fips204::{CryptoRng, RngCore, RngError};
use serde_json::Value;

use krusty_kms_crypto::{
    ml_dsa_estimation_signature, ml_dsa_key_commitment, ml_dsa_packed_key,
    ml_dsa_signature_payload, ml_dsa_verify, poseidon_hash_many, ML_DSA_KEY_FELTS,
    ML_DSA_PAYLOAD_FELTS, ML_DSA_PUBLIC_KEY_BYTES, ML_DSA_SIGNATURE_BYTES,
};
use starknet_types_core::felt::Felt;

const FIXTURE: &str = include_str!("fixtures/ml-dsa-known-answers.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("known-answer fixture parses")
}

fn bytes(value: &Value, field: &str) -> Vec<u8> {
    let text = value[field].as_str().expect("field is a string");
    hex::decode(text.trim_start_matches("0x")).expect("field is hex")
}

fn felt(value: &Value, field: &str) -> Felt {
    Felt::from_hex(value[field].as_str().expect("field is a string")).expect("field is a felt")
}

// A seeded SplitMix64. Test-only, and only ever used to make `fips204` keygen
// reproducible: the repo requires deterministic tests, and key quality is
// irrelevant to whether two verifiers agree. Never used for anything shipped.
struct SeededRng(u64);

impl RngCore for SeededRng {
    fn next_u32(&mut self) -> u32 {
        (self.next_u64() >> 32) as u32
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        for chunk in dest.chunks_mut(8) {
            let word = self.next_u64().to_le_bytes();
            let take = chunk.len();
            chunk.copy_from_slice(&word[..take]);
        }
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> std::result::Result<(), RngError> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl CryptoRng for SeededRng {}

// ---------------------------------------------------------------------------
// Known answers
// ---------------------------------------------------------------------------

#[test]
fn the_fixture_states_the_sizes_this_module_assumes() {
    let f = fixture();
    assert_eq!(bytes(&f, "publicKey").len(), ML_DSA_PUBLIC_KEY_BYTES);
    assert_eq!(bytes(&f, "signature").len(), ML_DSA_SIGNATURE_BYTES);
    assert_eq!(
        f["payloadFelts"].as_u64().expect("payloadFelts"),
        ML_DSA_PAYLOAD_FELTS as u64
    );
}

#[test]
fn the_packed_key_and_its_commitment_match_the_reference() {
    let f = fixture();
    let packed = ml_dsa_packed_key(&bytes(&f, "publicKey")).expect("packed key");
    assert_eq!(packed.len(), ML_DSA_KEY_FELTS);
    assert_eq!(
        ml_dsa_key_commitment(&bytes(&f, "publicKey")).expect("commitment"),
        felt(&f, "keyCommitment")
    );
    // The commitment is Poseidon over exactly the packed key and nothing else,
    // which is what lets the contract recompute it from the signature.
    assert_eq!(poseidon_hash_many(&packed), felt(&f, "keyCommitment"));
}

#[test]
fn the_payload_matches_the_reference_section_by_section() {
    let f = fixture();
    let payload = ml_dsa_signature_payload(
        &bytes(&f, "publicKey"),
        &felt(&f, "transactionHash"),
        &bytes(&f, "signature"),
    )
    .expect("payload");
    assert_eq!(payload.len(), ML_DSA_PAYLOAD_FELTS);

    for name in ["packedKey", "signature", "w", "m", "k"] {
        let section = &f["sections"][name];
        let offset = section["offset"].as_u64().expect("offset") as usize;
        let length = section["length"].as_u64().expect("length") as usize;
        let expected =
            Felt::from_hex(f["sectionDigests"][name].as_str().expect("digest")).expect("felt");
        assert_eq!(
            poseidon_hash_many(&payload[offset..offset + length]),
            expected,
            "payload section {name} does not match the reference"
        );
    }

    assert_eq!(
        poseidon_hash_many(&payload),
        felt(&f, "payloadDigest"),
        "payload digest does not match the reference"
    );
}

#[test]
fn the_reference_signature_verifies() {
    let f = fixture();
    assert!(ml_dsa_verify(
        &bytes(&f, "publicKey"),
        &felt(&f, "transactionHash"),
        &bytes(&f, "signature")
    ));
}

#[test]
fn verification_rejects_a_tampered_signature_and_a_wrong_hash() {
    let f = fixture();
    let key = bytes(&f, "publicKey");
    let hash = felt(&f, "transactionHash");

    let mut tampered = bytes(&f, "signature");
    tampered[0] ^= 1;
    assert!(!ml_dsa_verify(&key, &hash, &tampered));

    // The message is the hash, so a different hash is a different message even
    // though every byte of the signature is untouched.
    assert!(!ml_dsa_verify(
        &key,
        &(hash + Felt::ONE),
        &bytes(&f, "signature")
    ));
}

#[test]
fn verification_rejects_wrong_lengths_rather_than_panicking() {
    let f = fixture();
    let key = bytes(&f, "publicKey");
    let hash = felt(&f, "transactionHash");
    let signature = bytes(&f, "signature");

    assert!(!ml_dsa_verify(&key[..1951], &hash, &signature));
    assert!(!ml_dsa_verify(&key, &hash, &signature[..3308]));
    assert!(!ml_dsa_verify(&[], &hash, &[]));
}

#[test]
fn the_payload_builder_refuses_a_signature_that_does_not_verify() {
    let f = fixture();
    let mut tampered = bytes(&f, "signature");
    tampered[0] ^= 1;
    // It must refuse rather than emit a guessed layout: the contract's rejection
    // of a wrong payload carries no diagnosis.
    let error = ml_dsa_signature_payload(
        &bytes(&f, "publicKey"),
        &felt(&f, "transactionHash"),
        &tampered,
    )
    .expect_err("a tampered signature must not produce a payload");
    assert!(error.to_string().contains("does not verify"));
}

// ---------------------------------------------------------------------------
// The fee-estimation dummy
// ---------------------------------------------------------------------------

#[test]
fn the_estimation_signature_has_the_payload_shape_and_the_real_key() {
    let f = fixture();
    let key = bytes(&f, "publicKey");
    let dummy = ml_dsa_estimation_signature(&key).expect("estimation signature");

    assert_eq!(dummy.len(), ML_DSA_PAYLOAD_FELTS);
    // The packed key prefix is the real one, so the measured path is identical
    // to a real transaction's and it works against a class built before the
    // contract tolerated a wrong key.
    assert_eq!(
        dummy[..ML_DSA_KEY_FELTS],
        ml_dsa_packed_key(&key).expect("packed key")[..]
    );
    // Pure function of the key: no randomness, no stored fixture, no state.
    assert_eq!(dummy, ml_dsa_estimation_signature(&key).expect("again"));
}

#[test]
fn the_estimation_signature_is_not_a_valid_signature() {
    let f = fixture();
    let key = bytes(&f, "publicKey");
    let hash = felt(&f, "transactionHash");
    // It clears the verifier's three early exits so the estimate includes the
    // full cost, then fails the verdict. If this ever verified, the dummy would
    // be a forgery.
    assert!(!ml_dsa_verify(&key, &hash, &[0u8; ML_DSA_SIGNATURE_BYTES]));
    assert!(ml_dsa_estimation_signature(&key).is_ok());
}

#[test]
fn a_wrong_length_key_is_refused_everywhere() {
    for length in [0usize, 1951, 1953] {
        let key = vec![0u8; length];
        assert!(ml_dsa_packed_key(&key).is_err());
        assert!(ml_dsa_key_commitment(&key).is_err());
        assert!(ml_dsa_estimation_signature(&key).is_err());
    }
}

// ---------------------------------------------------------------------------
// Cross-check against a second implementation
// ---------------------------------------------------------------------------

// Signs the same 32 big-endian bytes with an empty context, which is the wire
// contract the phone signer and the Cairo verifier both use.
fn sign_with_fips204(rng: &mut SeededRng, hash: &Felt) -> (Vec<u8>, Vec<u8>, ml_dsa_65::PublicKey) {
    let (public, private) = ml_dsa_65::try_keygen_with_rng(rng).expect("keygen");
    let signature = private
        .try_sign_with_rng(rng, &hash.to_bytes_be(), &[])
        .expect("sign");
    let key_bytes = public.clone().into_bytes().to_vec();
    (key_bytes, signature.to_vec(), public)
}

#[test]
fn fresh_fips204_signatures_verify_and_produce_payloads() {
    let mut rng = SeededRng(0x5EED);
    for round in 0u64..6 {
        let hash = Felt::from(round * 0x9E37_79B9 + 1);
        let (key, signature, public) = sign_with_fips204(&mut rng, &hash);

        // Both implementations must accept the same triple.
        assert!(
            public.verify(
                &hash.to_bytes_be(),
                &signature.clone().try_into().expect("len"),
                &[]
            ),
            "round {round}: fips204 rejected its own signature"
        );
        assert!(
            ml_dsa_verify(&key, &hash, &signature),
            "round {round}: this verifier rejected a valid fips204 signature"
        );

        // And the witnesses must satisfy the integer identity for a real
        // signature, not just for the one in the fixture.
        let payload = ml_dsa_signature_payload(&key, &hash, &signature)
            .unwrap_or_else(|e| panic!("round {round}: payload failed: {e}"));
        assert_eq!(payload.len(), ML_DSA_PAYLOAD_FELTS);
        assert_eq!(
            payload[..ML_DSA_KEY_FELTS],
            ml_dsa_packed_key(&key).expect("packed key")[..]
        );
        assert_eq!(
            poseidon_hash_many(&payload[..ML_DSA_KEY_FELTS]),
            ml_dsa_key_commitment(&key).expect("commitment")
        );
    }
}

#[test]
fn a_signature_does_not_verify_under_a_different_key() {
    let mut rng = SeededRng(0xC0FFEE);
    let hash = Felt::from(7u32);
    let (first_key, first_signature, _) = sign_with_fips204(&mut rng, &hash);
    let (second_key, _, _) = sign_with_fips204(&mut rng, &hash);

    assert_ne!(first_key, second_key);
    assert!(ml_dsa_verify(&first_key, &hash, &first_signature));
    assert!(!ml_dsa_verify(&second_key, &hash, &first_signature));
    assert!(ml_dsa_signature_payload(&second_key, &hash, &first_signature).is_err());
}

#[test]
fn a_signature_does_not_verify_under_a_context() {
    // The wire contract is an empty FIPS 204 context. A signature made with a
    // context must be rejected, or a domain-separated signature from the phone
    // would be accepted for the wrong domain.
    let mut rng = SeededRng(0xBEEF);
    let hash = Felt::from(11u32);
    let (key, private) = {
        let (public, private) = ml_dsa_65::try_keygen_with_rng(&mut rng).expect("keygen");
        (public.into_bytes().to_vec(), private)
    };
    let contextual = private
        .try_sign_with_rng(&mut rng, &hash.to_bytes_be(), b"starknet")
        .expect("sign");
    assert!(!ml_dsa_verify(&key, &hash, &contextual));
}
