name: FFI

on:
  push:
    paths:
      - "crates/ffi/**"
      - "packages/kms-c/**"
      - ".github/workflows/ffi.yml"
  pull_request:
    paths:
      - "crates/ffi/**"
      - "packages/kms-c/**"
      - ".github/workflows/ffi.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - run: cargo build -p krusty-kms-cabi
      - run: cargo test -p krusty-kms-cabi
