name: Wrappers

on:
  push:
    paths:
      - "packages/**"
      - ".github/workflows/wrappers.yml"
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/wrappers.yml"

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      swift: ${{ steps.filter.outputs.swift }}
      jvm: ${{ steps.filter.outputs.jvm }}
      dart: ${{ steps.filter.outputs.dart }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3
        id: filter
        with:
          filters: |
            swift:
              - 'packages/kms-swift/**'
              - 'packages/kms-c/**'
            jvm:
              - 'packages/kms-jvm/**'
              - 'packages/kms-c/**'
            dart:
              - 'packages/kms-dart/**'
              - 'packages/kms-c/**'

  swift:
    needs: changes
    if: needs.changes.outputs.swift == 'true'
    runs-on: macos-14
    defaults:
      run:
        working-directory: packages/kms-swift
    steps:
      - uses: actions/checkout@v4
      - run: swift build

  jvm:
    needs: changes
    if: needs.changes.outputs.jvm == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/kms-jvm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          gradle-version: "8.10"
      - run: gradle classes

  dart:
    needs: changes
    if: needs.changes.outputs.dart == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/kms-dart
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
      - run: dart pub get
      - run: dart analyze
      - run: dart test
